class user {
  
  # webapp user
	user { 
    "webapp":
      ensure => present,
      #groups => ["sudo","wordpress"],
      membership => minimum,
      shell => "/bin/bash",
		  managehome => true,
		  password => '$1$Jp9gahZj$5fsPBPfikpkClvQASFkJ01' #password='default' (generated by `openssl passwd -1`),
		  #require => User["wordpress"],
        }

	# install ssh key
	class { "user-sshkey":
		user => "webapp",
		type => "rsa"
	}
	
	

}
