class user {
  
  # wordpress group
  group { "wordpress":
    ensure => "present",
  }

  # webapp user
	user { 
    "webapp":
      ensure => present,
      groups => ["sudo","wordpress"],
      membership => minimum,
      shell => "/bin/bash",
		  managehome => true,
		  password => 'Iecieviosei8mohcaKai', #password='default' (generated by `openssl passwd -1`),
		  require => Group["wordpress"],
  }

	# install ssh key
	class { "user-sshkey":
		user => "webapp",
		type => "rsa"
	}
	
	

}
