class user {

	user { 
                "webapp":
                  ensure => present,
                  groups => ["admin", "sudo"],
                  membership => minimum,
                  shell => "/bin/bash",
		  managehome => true,
		  password => '$1$Jp9gahZj$5fsPBPfikpkClvQASFkJ01' #password='default' (generated by `openssl passwd -1`)
        }

}
